GET https://localhost:5001/api/order

###
POST https://localhost:5001/api/order
Content-Type: application/json

{
"itemsIds": [
"1",
"4"
]
}

###
GET https://localhost:5001/api/order/0f8612a0-c08c-4ee8-b673-a3f25d563d10

###
PATCH https://localhost:5001/api/order/03beff68-bc70-4b34-8264-cc243f6ef686
Content-Type: application/json

[
{
"op": "replace",
"path": "/itemsIds",
"value": [
1,
2
]
}
]

### 'add' is replacing instead of adding. I am wondering why
PATCH https://localhost:5001/api/order/03beff68-bc70-4b34-8264-cc243f6ef686
Content-Type: application/json

[
{
"op": "add",
"path": "/itemsIds",
"value": [
6
]
}
]

###
PATCH https://localhost:5001/api/order/03beff68-bc70-4b34-8264-cc243f6ef686
Content-Type: application/json

[
{
"op": "remove",
"path": "/itemsIds"
}
]

###
DELETE https://localhost:5001/api/order/b5d4a2bc-c888-4994-99a3-c48891c440b2